import os
import uvicorn
import logging
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import List, Dict, Any, Optional

from agent.graph import graph
from langchain_core.messages import HumanMessage, AIMessage

# Production logging setup
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

app = FastAPI(title="Andromeda Agent API")

# Add production-ready CORS configuration allowing Vercel frontend domain
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:3000",
        "http://localhost:5173",
        "https://andromedatoolcallingagentui.vercel.app",
        os.environ.get("FRONTEND_URL", "https://andromedatoolcallingagentui.vercel.app")
    ],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class ChatRequest(BaseModel):
    messages: List[Dict[str, Any]] = []
    user_input: str
    web_search_enabled: Optional[bool] = False

@app.get("/health")
async def health_check():
    """Health endpoint for Railway infrastructure monitoring."""
    return {"status": "healthy", "service": "andromeda-backend"}

@app.post("/chat")
async def chat_endpoint(request: ChatRequest):
    """Chat endpoint for the Vercel frontend to consume."""
    try:
        # Convert dict messages to LangChain messages
        lc_messages = []
        for msg in request.messages:
            if msg.get("role") == "user":
                lc_messages.append(HumanMessage(content=msg.get("content", "")))
            elif msg.get("role") == "assistant":
                lc_messages.append(AIMessage(content=msg.get("content", "")))
        
        inputs = {
            "messages": lc_messages,
            "user_input": request.user_input,
            "web_search_enabled": request.web_search_enabled,
        }
        
        logger.info(f"Processing chat request: {request.user_input}")
        result = await graph.ainvoke(inputs, config={"recursion_limit": 100})
        
        if result and result.get("messages"):
            agent_response = result["messages"][-1]
            content = str(agent_response.content) if hasattr(agent_response, "content") else str(agent_response)
            
            # Format tool calls if they exist
            if hasattr(agent_response, "tool_calls") and agent_response.tool_calls:
                tool_info = "\n\n🔧 **Tools Used:**\n"
                for tool_call in agent_response.tool_calls:
                    tool_name = tool_call.get("name", "Unknown")
                    args = tool_call.get("args", {})
                    tool_info += f"- **{tool_name}**: {args}\n"
                content += tool_info
                
            return {"response": content}
        else:
            logger.error("No response generated by the agent graph.")
            raise HTTPException(status_code=500, detail="No response generated")
            
    except Exception as e:
        logger.error(f"Error during chat processing: {str(e)}")
        # Error handling for deployment environments
        raise HTTPException(status_code=500, detail=str(e))

if __name__ == "__main__":
    # Configure PORT from process.env.PORT equivalent
    port = int(os.environ.get("PORT", 8000))
    # Ensure server binds to 0.0.0.0
    uvicorn.run("server:app", host="0.0.0.0", port=port, log_level="info")
