"""PDF report generation tools.

Provides functionality to generate styled PDF reports from data.
"""

import os
from datetime import datetime
from pathlib import Path
from typing import Optional

from langchain.tools import tool
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Spacer, Table, TableStyle, Paragraph

from agent.async_utils import run_in_thread


def _generate_pdf_report_sync(
    title: str,
    content: str,
    output_path: str = "./reports/report.pdf",
    subtitle: Optional[str] = None,
) -> str:
    """Generate a styled PDF report.

    Args:
        title: The title of the report
        content: The main content of the report
        output_path: The path where the PDF will be saved (default: ./reports/report.pdf)
        subtitle: Optional subtitle for the report

    Returns:
        A message indicating success or failure with the file path
    """
    try:
        # Create reports directory if it doesn't exist
        output_dir = Path(output_path).parent
        output_dir.mkdir(parents=True, exist_ok=True)

        # Create PDF document
        doc = SimpleDocTemplate(
            output_path,
            pagesize=letter,
            rightMargin=0.75 * inch,
            leftMargin=0.75 * inch,
            topMargin=0.75 * inch,
            bottomMargin=0.75 * inch,
        )

        # Get sample styles
        styles = getSampleStyleSheet()

        # Create custom styles
        title_style = ParagraphStyle(
            "CustomTitle",
            parent=styles["Heading1"],
            fontSize=24,
            textColor=colors.HexColor("#2c3e50"),
            spaceAfter=30,
            alignment=1,  # Center
        )

        subtitle_style = ParagraphStyle(
            "CustomSubtitle",
            parent=styles["Heading2"],
            fontSize=14,
            textColor=colors.HexColor("#34495e"),
            spaceAfter=20,
            alignment=1,  # Center
        )

        body_style = ParagraphStyle(
            "CustomBody",
            parent=styles["BodyText"],
            fontSize=11,
            leading=14,
            textColor=colors.HexColor("#2c3e50"),
            spaceAfter=12,
        )

        # Build content
        story = []

        # Add title
        story.append(Paragraph(title, title_style))

        # Add subtitle if provided
        if subtitle:
            story.append(Paragraph(subtitle, subtitle_style))

        # Add date
        date_style = ParagraphStyle(
            "DateStyle",
            parent=styles["Normal"],
            fontSize=10,
            textColor=colors.HexColor("#7f8c8d"),
            alignment=1,
        )
        story.append(Paragraph(f"Generated on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", date_style))
        story.append(Spacer(1, 0.3 * inch))

        # Add horizontal line
        line_table = Table(
            [[""]],
            colWidths=[7.5 * inch],
        )
        line_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#ecf0f1")),
                    ("LINEBELOW", (0, 0), (-1, -1), 2, colors.HexColor("#3498db")),
                    ("ROWHEIGHTS", (0, 0), (-1, -1), 0.05 * inch),
                ]
            )
        )
        story.append(line_table)
        story.append(Spacer(1, 0.2 * inch))

        # Add main content (split by lines)
        content_lines = content.split("\n")
        for line in content_lines:
            if line.strip():
                story.append(Paragraph(line.strip(), body_style))
            else:
                story.append(Spacer(1, 0.1 * inch))

        # Add footer
        story.append(Spacer(1, 0.3 * inch))
        footer_style = ParagraphStyle(
            "FooterStyle",
            parent=styles["Normal"],
            fontSize=9,
            textColor=colors.HexColor("#95a5a6"),
            alignment=1,
        )
        story.append(Paragraph("Generated by Andromeda Agent", footer_style))

        # Build PDF
        doc.build(story)

        file_size = os.path.getsize(output_path)
        return f"PDF report successfully generated: {output_path} ({file_size} bytes)"

    except Exception as e:
        return f"Error generating PDF report: {str(e)}"


@tool
async def generate_pdf_report(
    title: str,
    content: str,
    output_path: str = "./reports/report.pdf",
    subtitle: Optional[str] = None,
) -> str:
    """Generate a styled PDF report."""
    return await run_in_thread(
        _generate_pdf_report_sync, title, content, output_path, subtitle
    )


def _generate_table_report_sync(
    title: str,
    table_data: list,
    output_path: str = "./reports/table_report.pdf",
) -> str:
    """Generate a PDF report with a data table.

    Args:
        title: The title of the report
        table_data: A list of lists representing table data (first row is header)
        output_path: The path where the PDF will be saved

    Returns:
        A message indicating success or failure with the file path
    """
    try:
        # Create reports directory if it doesn't exist
        output_dir = Path(output_path).parent
        output_dir.mkdir(parents=True, exist_ok=True)

        # Create PDF document
        doc = SimpleDocTemplate(
            output_path,
            pagesize=letter,
            rightMargin=0.5 * inch,
            leftMargin=0.5 * inch,
            topMargin=0.5 * inch,
            bottomMargin=0.5 * inch,
        )

        styles = getSampleStyleSheet()

        title_style = ParagraphStyle(
            "CustomTitle",
            parent=styles["Heading1"],
            fontSize=20,
            textColor=colors.HexColor("#2c3e50"),
            spaceAfter=20,
            alignment=1,
        )

        # Build content
        story = []
        story.append(Paragraph(title, title_style))
        story.append(Spacer(1, 0.2 * inch))

        # Create table
        if table_data:
            table = Table(table_data)
            table.setStyle(
                TableStyle(
                    [
                        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#3498db")),
                        ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
                        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                        ("FONTSIZE", (0, 0), (-1, 0), 12),
                        ("BOTTOMPADDING", (0, 0), (-1, 0), 12),
                        ("BACKGROUND", (0, 1), (-1, -1), colors.beige),
                        ("GRID", (0, 0), (-1, -1), 1, colors.black),
                        ("ROWHEIGHTS", (0, 0), (-1, -1), 0.3 * inch),
                    ]
                )
            )
            story.append(table)

        # Build PDF
        doc.build(story)

        file_size = os.path.getsize(output_path)
        return f"Table PDF report successfully generated: {output_path} ({file_size} bytes)"

    except Exception as e:
        return f"Error generating table PDF report: {str(e)}"


@tool
async def generate_table_report(
    title: str,
    table_data: list,
    output_path: str = "./reports/table_report.pdf",
) -> str:
    """Generate a PDF report with a data table."""
    return await run_in_thread(
        _generate_table_report_sync, title, table_data, output_path
    )


__all__ = ["generate_pdf_report", "generate_table_report"]


