"""Comprehensive Email Processing Agent - Process unread emails with detailed tracking."""
from __future__ import annotations
import argparse
import logging
import sys
import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional, Any
from dotenv import load_dotenv
from langchain_groq import ChatGroq
from langchain_core.messages import HumanMessage
# Add src to path for local imports
_SRC_ROOT = Path(__file__).resolve().parent
if str(_SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(_SRC_ROOT))
from gmail_agent import (  # noqa: E402
    GmailAgentConfig,
    configure_logging,
    generate_reply_with_ollama,
    get_gmail_service,
    get_message,
    list_unread_messages,
    mark_as_read,
    send_reply,
    ParsedEmail,
)
load_dotenv()
logger = logging.getLogger("email_processor")
@dataclass
class EmailProcessingSummary:
    """Tracks statistics for email processing."""
    total_unread: int = 0
    replied_successfully: int = 0
    skipped: int = 0
    failed: int = 0
    skip_reasons: dict[str, int] = field(default_factory=dict)
    failed_reasons: dict[str, int] = field(default_factory=dict)
    processed_messages: list[tuple[str, bool, Optional[str]]] = field(default_factory=list)
    def add_skip(self, msg_id: str, reason: str) -> None:
        """Record a skipped email."""
        self.skipped += 1
        self.skip_reasons[reason] = self.skip_reasons.get(reason, 0) + 1
        self.processed_messages.append((msg_id, False, reason))
    def add_failure(self, msg_id: str, reason: str) -> None:
        """Record a failed email."""
        self.failed += 1
        self.failed_reasons[reason] = self.failed_reasons.get(reason, 0) + 1
        self.processed_messages.append((msg_id, False, reason))
    def add_success(self, msg_id: str) -> None:
        """Record a successfully processed email."""
        self.replied_successfully += 1
        self.processed_messages.append((msg_id, True, None))
    def get_report(self) -> str:
        """Generate formatted summary report."""
        lines = [
            "=" * 70,
            "EMAIL PROCESSING SUMMARY REPORT",
            "=" * 70,
            "",
            f"Total unread emails found: {self.total_unread}",
            f"Emails replied successfully: {self.replied_successfully}",
            f"Emails skipped: {self.skipped}",
            f"Emails failed: {self.failed}",
            "",
        ]
        if self.skip_reasons or self.failed_reasons:
            lines.append("REASONS FOR SKIPPED OR FAILED EMAILS:")
            lines.append("-" * 70)
            if self.skip_reasons:
                lines.append("\nSkipped (not requiring response):")
                for reason, count in sorted(
                    self.skip_reasons.items(), key=lambda x: x[1], reverse=True
                ):
                    lines.append(f"  • {reason}: {count} email(s)")
            if self.failed_reasons:
                lines.append("\nFailed to process:")
                for reason, count in sorted(
                    self.failed_reasons.items(), key=lambda x: x[1], reverse=True
                ):
                    lines.append(f"  • {reason}: {count} email(s)")
        if self.replied_successfully > 0:
            lines.append(
                f"\nConfirmation: ✓ {self.replied_successfully} processed email(s) "
                "were marked as Read."
            )
        lines.append("")
        lines.append("=" * 70)
        return "\n".join(lines)
def is_spam_or_promotional(email: ParsedEmail) -> bool:
    """Check if email is spam, promotional, or automated notification."""
    subject = (email.get("subject") or "").lower()
    sender = (email.get("sender") or "").lower()
    body = (email.get("body") or "").lower()[:500]
    spam_keywords = [
        "verify your account", "confirm your identity", "click here immediately",
        "act now", "limited time offer", "click below", "claim your", "winner",
        "congratulations",
    ]
    promo_keywords = [
        "unsubscribe", "promotional", "marketing", "newsletter", "sale",
        "discount", "offer", "coupon", "deal",
    ]
    auto_keywords = [
        "do not reply", "do-not-reply", "noreply", "no-reply", "autogenerated",
        "automated message", "system notification", "password reset",
        "confirmation code", "verification code",
    ]
    suspicious_senders = ["noreply@", "no-reply@", "notifications@", "alerts@", "verify@"]
    for pattern in suspicious_senders:
        if pattern in sender:
            return True
    combined_text = subject + " " + body
    if any(keyword in combined_text for keyword in spam_keywords):
        return True
    if any(keyword in combined_text for keyword in promo_keywords):
        return True
    if any(keyword in combined_text for keyword in auto_keywords):
        return True
    return False
def generate_reply_text(
    email: ParsedEmail, config: GmailAgentConfig, use_groq: bool = True
) -> Optional[str]:
    """Generate a professional, context-aware reply."""
    prompt = (
        "You are a professional email assistant. Write a concise, courteous reply to the sender. "
        "Address their message directly, include clear next steps when appropriate, "
        "and limit the reply to 2-3 short paragraphs. "
        "Do NOT include subject line, greeting, or closing — only the body text.\n\n"
        f"From: {email['sender']}\n"
        f"Subject: {email['subject']}\n\n"
        "Original message:\n"
        f"{email['body']}\n\n"
        "Reply:"
    )
    if use_groq:
        try:
            groq_api_key = os.getenv("GROQ_API_KEY")
            if groq_api_key:
                llm = ChatGroq(
                    model="llama-3.1-8b-instant",
                    temperature=0.7,
                    api_key=groq_api_key,
                    max_tokens=300,
                )
                response = llm.invoke([HumanMessage(content=prompt)])
                if response and response.content:
                    return str(response.content).strip()
        except Exception as exc:
            logger.debug(f"Groq reply generation failed: {exc}, trying Ollama...")
    try:
        reply = generate_reply_with_ollama(email, config)
        if reply:
            return reply
    except Exception as exc:
        logger.debug(f"Ollama reply generation failed: {exc}")
    return None
def process_single_email(
    service: Any,
    config: GmailAgentConfig,
    msg_id: str,
    summary: EmailProcessingSummary,
    use_groq: bool = True,
) -> bool:
    """Process a single unread email."""
    try:
        email = get_message(service, config, msg_id)
        logger.info(
            f"Processing: {email['sender'][:40]} | {email['subject'][:50]}"
        )
        if is_spam_or_promotional(email):
            reason = "Spam, promotional, or automated notification email"
            logger.info(f"Skipping: {reason}")
            summary.add_skip(msg_id, reason)
            return False
        reply_text = generate_reply_text(email, config, use_groq)
        if not reply_text:
            reason = "Could not generate reply (LLM unavailable)"
            logger.warning(f"Failed to generate reply: {reason}")
            summary.add_failure(msg_id, reason)
            return False
        sent = send_reply(service, config, email, reply_text)
        if not sent:
            reason = f"Failed to send reply to {email['sender']}"
            logger.error(reason)
            summary.add_failure(msg_id, reason)
            return False
        if not mark_as_read(service, config, msg_id):
            logger.warning(f"Reply sent but failed to mark {msg_id} as read")
        logger.info(f"Successfully replied to: {email['sender']}")
        summary.add_success(msg_id)
        return True
    except Exception as exc:
        reason = f"Error processing message: {str(exc)[:80]}"
        logger.exception(reason)
        summary.add_failure(msg_id, reason)
        return False
def process_all_unread_emails(
    limit: Optional[int] = None,
    config: Optional[GmailAgentConfig] = None,
    use_groq: bool = True,
) -> EmailProcessingSummary:
    """Process all unread inbox emails end-to-end."""
    cfg = config or GmailAgentConfig.from_env()
    configure_logging(cfg.log_level)
    logger.info("=" * 70)
    logger.info("EMAIL PROCESSING AGENT STARTED")
    logger.info("=" * 70)
    try:
        service = get_gmail_service(cfg)
        logger.info("✓ Gmail OAuth connection established")
    except Exception as exc:
        logger.error(f"Failed to establish Gmail connection: {exc}")
        summary = EmailProcessingSummary()
        summary.add_failure("SYSTEM", f"Gmail connection failed: {exc}")
        return summary
    try:
        message_refs = list_unread_messages(service, cfg)
        logger.info(f"✓ Found {len(message_refs)} unread email(s)")
    except Exception as exc:
        logger.error(f"Failed to list unread messages: {exc}")
        summary = EmailProcessingSummary()
        summary.add_failure("SYSTEM", f"Failed to fetch unread emails: {exc}")
        return summary
    summary = EmailProcessingSummary()
    summary.total_unread = len(message_refs)
    if not message_refs:
        logger.info("No unread emails to process")
        return summary
    logger.info("-" * 70)
    for index, msg_ref in enumerate(message_refs, start=1):
        if limit and summary.replied_successfully + summary.skipped + summary.failed >= limit:
            logger.info(f"Reached processing limit of {limit} emails")
            break
        msg_id = msg_ref.get("id")
        if not msg_id:
            logger.warning(f"Message {index}: Missing ID, skipping")
            continue
        logger.info(f"[{index}/{len(message_refs)}] Processing email...")
        process_single_email(service, cfg, msg_id, summary, use_groq)
    logger.info("-" * 70)
    return summary
def _parse_args(argv: Optional[list[str]] = None) -> argparse.Namespace:
    """Parse CLI arguments."""
    parser = argparse.ArgumentParser(
        description="Process unread Gmail emails with AI-generated replies.",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=None,
        help="Maximum number of emails to process (default: process all)",
    )
    parser.add_argument(
        "--use-ollama-only",
        action="store_true",
        help="Use only Ollama for replies (skip Groq)",
    )
    return parser.parse_args(argv)
def main(argv: Optional[list[str]] = None) -> int:
    """CLI entrypoint."""
    args = _parse_args(argv)
    config = GmailAgentConfig.from_env()
    configure_logging(config.log_level)
    try:
        use_groq = not args.use_ollama_only
        summary = process_all_unread_emails(
            limit=args.limit,
            config=config,
            use_groq=use_groq,
        )
        print("\n")
        print(summary.get_report())
        return 0 if summary.failed == 0 else 1
    except Exception as exc:
        logger.exception(f"Fatal error: {exc}")
        return 1
if __name__ == "__main__":
    raise SystemExit(main())
